# Generated by Django 4.0.3 on 2022-03-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
