# Generated by Django 4.0.3 on 2022-03-27 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_person_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 34, 34, 542209, tzinfo=utc), verbose_name='Date Ended'),
        ),
        migrations.AddField(
            model_name='group',
            name='starting_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 34, 34, 541829, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
