# Generated by Django 4.0.3 on 2022-03-27 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_group_ending_date_group_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ending_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Ended'),
        ),
        migrations.AlterField(
            model_name='group',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Started'),
        ),
    ]
