# Generated by Django 4.0.3 on 2022-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_group_ending_date_alter_group_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cups',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=50),
        ),
    ]
