# Generated by Django 4.0.3 on 2022-03-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_person_image'),
        ('polls', '0006_person_cups'),
    ]

    operations = [
    ]
