# Generated by Django 4.0.3 on 2022-03-27 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_merge_0004_person_image_0006_person_cups'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Recorded'),
        ),
        migrations.AlterField(
            model_name='group',
            name='days_left',
            field=models.IntegerField(default=1),
        ),
    ]
