# Generated by Django 4.0.3 on 2022-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_person_date_recorded_alter_group_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='days_left',
            field=models.IntegerField(default=7),
        ),
    ]
